# Generated by Django 3.0.8 on 2021-04-11 20:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('matricula', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=12, null=True)),
                ('estatus', models.CharField(choices=[('Activo', 'Activo'), ('Baja', 'Baja'), ('Graduado', 'Graduado')], default='Activo', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_carrera', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Finanza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(max_length=100)),
                ('estatus', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciclo', models.CharField(max_length=100)),
                ('grado', models.CharField(max_length=5)),
                ('grupo', models.CharField(max_length=5)),
                ('parcial', models.CharField(choices=[('Cuatrimestre', 'Cuatrimestre'), ('Semestre', 'Semestre')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pago', models.CharField(max_length=200)),
                ('monto', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Plantel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion', models.CharField(max_length=100)),
                ('reactor', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Tramite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_tramitado', models.DateTimeField(auto_now_add=True, null=True)),
                ('pago_parcial', models.CharField(max_length=100)),
                ('proximo_pago', models.DateField(null=True)),
                ('monto_a_pagar', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('Completado', 'Completado'), ('En Progreso', 'En Progreso'), ('Deuda', 'Deuda')], max_length=100)),
                ('clave_alumno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pagos.Alumno')),
                ('clave_pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pagos.Pago')),
                ('encargado_tramite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pagos.Finanza')),
            ],
        ),
        migrations.AddField(
            model_name='finanza',
            name='clave_plantel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pagos.Plantel'),
        ),
        migrations.AddField(
            model_name='finanza',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Cobro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateTimeField(auto_now_add=True, null=True)),
                ('monto', models.CharField(max_length=150)),
                ('clave_tramite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pagos.Tramite')),
            ],
        ),
        migrations.AddField(
            model_name='alumno',
            name='clave_carrera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pagos.Carrera'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='clave_plantel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pagos.Plantel'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='grupo',
            field=models.ManyToManyField(blank=True, to='pagos.Grupo'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
