# Generated by Django 3.0.8 on 2021-04-12 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0002_auto_20210411_2125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='apellido_materno',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='apellido_paterno',
        ),
        migrations.AddField(
            model_name='alumno',
            name='apellido',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
