# Generated by Django 3.0.8 on 2021-04-12 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0003_auto_20210412_0217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tramite',
            name='monto_a_pagar',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tramite',
            name='proximo_pago',
            field=models.DateField(blank=True, null=True),
        ),
    ]
