# Generated by Django 3.0.8 on 2021-04-13 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0004_auto_20210412_1723'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tramite',
            old_name='monto_a_pagar',
            new_name='monto_adeudo',
        ),
    ]
