# Generated by Django 3.0.8 on 2021-04-14 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0005_auto_20210413_0217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='monto',
            field=models.IntegerField(max_length=100),
        ),
    ]
